version: "3.7"

services:
  dnsmasq-adblock:
    container_name: dnsmasq-adblock
    image: istitch07/dnsmasq-adblock
    restart: unless-stopped
    volumes:
      - ./conf:/opt/dnsmasq
    ports:
      - 53:53/udp
    cap_add:
      - NET_ADMIN
